# on events
on:
  push

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
      - name: Prep
        run: mkdir mfr-ubuntu && cp -r assets mfr-ubuntu/assets
      - name: Build
        run: go build -o mfr-ubuntu/Metroid-Fusion-Remastered     
      - uses: papeloto/action-zip@v1
        with:
          files: mfr-ubuntu/
          dest: mfr-ubuntu.zip
      - uses: actions/upload-artifact@v2
        with:
          name: METROID FUSION REMASTERED (Ubuntu)
          path: mfr-ubuntu.zip
